### PR TITLE
fix unsafe method

### LINKED ISSUE #1: Unsafe method
https://github.com/KatarzynaBurdzy/To-Do-List/blob/45f3d5be865fb83fb7315eea2e4c8ced52a74a9b/list.js#L34
Zrzut ekranu 2022-12-2 o 12 00 58

Instead of inserting something with user input directly into HTML check other methods and treat the input as plain text. Maybe you should combine techniques such as appendChild and textContent etc.

Please before the following change create a side branch, next PR, and mark me as a reviewer so I could check your code before implementing it into the main branch.

### PR DESCRIPTION
**Pull request by ajankowy035**
@KatarzynaBurdzy  you need to remember to create a pull request once you want to merge your code to the main branch :)

### CODE REVIEW

File: list.js [hunk 1]
```diff
@@ -9,45 +9,60 @@ const liNote = document.querySelector(".note");
...
-// add TASK to the listArr so later you can remove it
-const addListArr = function (toDo, note, id, done, trash) {
-  listArr.push({
-    name: toDo,
-    note: note,
-    id: id,
-    done: false,
-    trash: false,
+const createListEl = function (toDo, note) {
+  // Creating new elements
```
Comment (ajankowy035) [inline list.js]: Don't use too many comments, instead focus on using the most descriptive names of variables and functions - so the reader will not need any comments :) 

I understand you might need those comments to establish and deeply understand what is happening, hovewer remember that comments are like trashes - use them only when are necessary to understand what is going on in the code (such as in the complex math algorithm)

File: list.js [hunk 2]
```diff
@@ -9,45 +9,60 @@ const liNote = document.querySelector(".note");
...
+  btnMore.addEventListener("click", () => newNote.classList.toggle("hidden"));
+
+  // Appending children
+  newLi.appendChild(h3Text);
+  newLi.appendChild(btnTrash);
+  newLi.appendChild(btnMore);
+  newLi.appendChild(newNote);
+  unorderedList.appendChild(newLi);
+
+  console.log(newLi);
```
Comment (ajankowy035) [inline list.js]: Is that needed? If you are using console log to debug your code - remove it before merge

File: style.css [hunk 3]
```diff
@@ -62,42 +90,22 @@ main {
...
 
-.btn-cancel {
+.btn-trash {
   background-color: red;
+  margin-left: 20px;
 }
 
-.btn-cancel:active {
+.btn-trash:active {
   background-color: darkred;
```
Comment (ajankowy035) [inline style.css]: this is not a good practice to use named colors instead of using HEX or RGB :) If you want to use names, establish them earlier with the desired HEX code for example using variables [w3schools](https://www.w3schools.com/css/css3_variables.asp)

Comment (KatarzynaBurdzy) [reply style.css]: Those are temporary colors, I'm going to change them soon.

File: list.js (hunk 2 above)
Comment (KatarzynaBurdzy) [reply list.js]: I used it to debug and I must've overlooked it as I was reviewing my code.

Comment (ajankowy035) [reply list.js]: Yeah - I totally understand - you needed it.

File: list.js (hunk 1 above)
Comment (ajankowy035) [reply list.js]: Yeah - I totally understand - you needed them. And it's not the issue in this case. However, remember when creating code in. the future - it's one of the gold rules of clean code :) Descriptive variables names
